Solved #442- Proximity to POI
Akshat111111/Hedging-of-Financial-Derivatives pull request #451
Opened 2024-07-07 16:28 UTC by Aditi22Bansal

## 🛠️ Related Issue

- Closes #[issue_number]
#442 
## 📝 Description

[Provide a concise description of the changes. Include the purpose and any relevant context or details.]

## 🔍 Type of PR

- [ ] 🐛 Bug fix
- [x] ✨ Feature enhancement
- [ ] 📚 Documentation update
- [ ] 🛑 Other (specify): _______________

## 📸 Screenshots / 🎥 Videos (if applicable)

[Attach screenshots or videos]

## ✅ Checklist

- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## ℹ️ Additional Context

[Include any additional context or information that might assist reviewers in understanding the changes]

2024-07-07 16:28 UTC, Aditi22Bansal commented
@Akshat111111 
Kindly review, add labels and merge

2024-07-07 18:55 UTC, Aditya-dom requested changes

2024-07-07 18:55 UTC, Aditya-dom commented on Finacial Domain/Proximity to POI/POI.py
> +    ('poly_features', PolynomialFeatures(degree=2, include_bias=False)),
Remove 'degree=2' to be set in GridSearchCV

```suggestion
    ('poly_features', PolynomialFeatures( include_bias=False)),
```

2024-07-07 18:55 UTC, Aditya-dom commented on Finacial Domain/Proximity to POI/POI.py
> +    'model__alpha': [0.1, 1.0, 10.0] if 'alpha' in grid_search.best_params_ else [0]
Directly set 'alpha' for all models

```suggestion
    'model__alpha': [0.1, 1.0, 10.0]
```

2024-07-08 14:02 UTC, Aditi22Bansal commented
@Akshat111111 
@Aditya-dom 
Kindly review and merge

2024-07-08 14:07 UTC, Aditya-dom approved these changes
LMGT!!

2024-07-08 14:13 UTC, Aditi22Bansal commented
@Aditya-dom 
Kindly add labels

2024-07-08 14:13 UTC, Aditi22Bansal commented
@Aditya-dom 
For gssoc 24 leaderboard

2024-07-09 06:46 UTC, Akshat111111 reviewed
yeah, it works

2024-07-09 06:46 UTC, Akshat111111 commented
@Aditya-dom are you a part of gssoc ??

2024-07-09 06:47 UTC, merged

2024-07-09 07:43 UTC, Aditya-dom commented
> @Aditya-dom are you a part of gssoc ??

Yup @Akshat111111 
I received an email assigning me to review the PRs as the deadlines are approaching.

2024-07-11 03:55 UTC, Akshat111111 commented
from what??